### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by shiddarthbista** [Masedko/glyph#1]
I saw a glyph tracker in reddit https://s3rbug.github.io/whousedglyph/ and looking at their code I wanted to do like a personal project.
i saw that you added their url to the CORS . 
Could you do the same for me as well? I just use it for fun with friends so it wont hit your api a lot.
https://shiddarthbista.github.io/

**Comment by Andrii-Hladkyi-Masedko** [comment]
We did this project together. S3rbug and me. So, I am sorry to tell you that I cannot add your project to CORS. But you can host this project by yourself.

**Comment by shiddarthbista** [comment]
Thank you .
